component:
  name: cart
  version: 4.0.3
configMap:
  create: yes
  name: cart
  data:
    REDIS_HOST: redis-master
    CATALOGUE_HOST: catalogue
    CATALOGUE_PORT: "8080"
service:
  containerPort: 8080
resources:
  limits:
    cpu: 350m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

